### ISSUE TITLE
Is there a sample database?

### ISSUE THREAD

**Issue by Wim386** [Provincie-Zuid-Holland/Omgevingsbeleid-API#38]
The API needs a database to fetch the asked for data. A description of which tables, columns and types are needed, would be welcome. This may be in the form of a sample database, or in the form of a ddl script

**Comment by IngmarEmons** [comment]
[Export Omgevingsbeleid DDL.zip](https://github.com/Provincie-Zuid-Holland/Omgevingsbeleid-API/files/6733588/Export.Omgevingsbeleid.DDL.zip)

**Comment by IngmarEmons** [comment]
I've exported the DDL of the database for you to start with.

**Comment by Swendude** [comment]
The database above will not do. The system is set up modulair so the database scheme will eventually be generated by the system itself. We did not prioritize this in our sprint planning ATM. 

Closing until relevant and time has been allocated.
